# Generated by Django 4.0.4 on 2022-06-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyroomseat',
            name='stairs',
            field=models.IntegerField(default=1, verbose_name='靠近走廊'),
        ),
    ]
