# Generated by Django 4.0.4 on 2022-06-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0006_alter_leisureseat_power_alter_leisureseat_stairs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyroomseat',
            name='status',
            field=models.IntegerField(default=0, verbose_name='座位状态'),
        ),
    ]
