# Generated by Django 4.0.4 on 2022-05-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeisureSeat',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='座位编号')),
                ('status', models.IntegerField(default=0)),
                ('floor', models.CharField(max_length=5, verbose_name='所在楼层')),
                ('power', models.IntegerField(default=1, verbose_name='拥有电源')),
                ('stairs', models.IntegerField(default=1, verbose_name='靠近楼梯')),
            ],
        ),
        migrations.CreateModel(
            name='StandardSeat',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='座位编号')),
                ('status', models.IntegerField(default=0)),
                ('floor', models.CharField(max_length=5, verbose_name='所在楼层')),
                ('power', models.IntegerField(default=1, verbose_name='拥有电源')),
                ('stairs', models.IntegerField(default=1, verbose_name='靠近楼梯')),
            ],
        ),
        migrations.CreateModel(
            name='StudyRoomSeat',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='座位编号')),
                ('status', models.IntegerField(default=0)),
                ('floor', models.CharField(max_length=5, verbose_name='所在楼层')),
                ('power', models.IntegerField(default=1, verbose_name='拥有电源')),
                ('stairs', models.IntegerField(default=1, verbose_name='靠近楼梯')),
            ],
        ),
        migrations.CreateModel(
            name='TotalSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudyRoom', models.CharField(max_length=100, verbose_name='自习室座位')),
                ('Standard', models.CharField(max_length=100, verbose_name='标准座位')),
                ('Leisure', models.CharField(max_length=100, verbose_name='休闲座位')),
            ],
        ),
    ]
