# Generated by Django 4.0.4 on 2022-05-31 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('User_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='学号')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='邮箱')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='user_seat',
            fields=[
                ('User_id', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='学号')),
                ('seat_id', models.CharField(default='未预约座位', max_length=1000, verbose_name='所坐位置')),
                ('status', models.CharField(default='未预约', max_length=100, verbose_name='用户状态')),
                ('timeStatus', models.CharField(default=0, max_length=1000)),
            ],
        ),
    ]
