# Generated by Django 4.0.4 on 2022-07-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='integral',
            field=models.IntegerField(default=5, max_length=10, verbose_name='信誉积分'),
        ),
    ]
