# Generated by Django 4.1.2 on 2022-10-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order_seat',
            fields=[
                ('User_id', models.CharField(max_length=100, verbose_name='学号')),
                ('Seat_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='座位编号')),
                ('day', models.CharField(max_length=100, verbose_name='日期')),
                ('day_time', models.CharField(max_length=100, verbose_name='时间段')),
            ],
        ),
    ]
